default_context:
  project_name: 'modernrainforest'
  project_slug: 'modernrainforest'
  domain_main: 'modernrainforest.com'
  domain_staging: 'stag.modernrainforest.com'
  docker_swarm_stack_name_main: 'modernrainforest-com'
  docker_swarm_stack_name_staging: 'stag-modernrainforest-com'
  secret_key: '8b4d65f8bbce6f0f696a9d42829191d3af3d621468fbeddf4442124d17c60185'
  first_superuser: 'raceychan@gmail.com'
  first_superuser_password: '4844159acc'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.modernrainforest.com", "https://stag.modernrainforest.com", "https://modernrainforest.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'raceychan'
  smtp_password: '4844159acc'
  smtp_emails_from_email: 'info@modernrainforest.com'
  postgres_password: '4844159acc'
  pgadmin_default_user: 'raceychan@gmail.com'
  pgadmin_default_user_password: '4844159acc'
  traefik_constraint_tag: 'modernrainforest.com'
  traefik_constraint_tag_staging: 'stag.modernrainforest.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:4844159acc'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
